import {
  BuildPlan,
  SavedToolItem,
  ToolOption,
  UserSettings,
} from "@/types/buildsy";
import { calculatePlanBudget, SHOWCASE_BUILD_PLAN } from "@/lib/plan-engine";

const PLANS_KEY = "buildsy_plans_v1";
const SAVED_TOOLS_KEY = "buildsy_saved_tools_v1";
const SETTINGS_KEY = "buildsy_settings_v1";

export const DEFAULT_SETTINGS: UserSettings = {
  preferredRegion: "USD",
  geminiApiKey: "",
  founderName: "Solo Founder",
  defaultSkillLevel: "Full-stack / AI-assisted builder",
};

export function getSavedPlans(): BuildPlan[] {
  if (typeof window === "undefined") return [SHOWCASE_BUILD_PLAN];
  try {
    const raw = window.localStorage.getItem(PLANS_KEY);
    if (!raw) {
      window.localStorage.setItem(
        PLANS_KEY,
        JSON.stringify([SHOWCASE_BUILD_PLAN])
      );
      return [SHOWCASE_BUILD_PLAN];
    }
    const parsed = JSON.parse(raw) as BuildPlan[];
    return parsed.length > 0 ? parsed : [SHOWCASE_BUILD_PLAN];
  } catch {
    return [SHOWCASE_BUILD_PLAN];
  }
}

export function savePlanToStorage(plan: BuildPlan): BuildPlan[] {
  if (typeof window === "undefined") return [plan];
  const existing = getSavedPlans();
  const idx = existing.findIndex((p) => p.id === plan.id);
  let updated: BuildPlan[];
  if (idx >= 0) {
    updated = [...existing];
    updated[idx] = plan;
  } else {
    updated = [plan, ...existing];
  }
  window.localStorage.setItem(PLANS_KEY, JSON.stringify(updated));
  return updated;
}

export function deletePlanFromStorage(planId: string): BuildPlan[] {
  if (typeof window === "undefined") return [SHOWCASE_BUILD_PLAN];
  const existing = getSavedPlans().filter((p) => p.id !== planId);
  const finalPlans = existing.length > 0 ? existing : [SHOWCASE_BUILD_PLAN];
  window.localStorage.setItem(PLANS_KEY, JSON.stringify(finalPlans));
  return finalPlans;
}

export function getSavedTools(): SavedToolItem[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(SAVED_TOOLS_KEY);
    return raw ? (JSON.parse(raw) as SavedToolItem[]) : [];
  } catch {
    return [];
  }
}

export function toggleSavedTool(
  tool: ToolOption,
  categoryName: string,
  planTitle?: string
): SavedToolItem[] {
  if (typeof window === "undefined") return [];
  const current = getSavedTools();
  const exists = current.some((item) => item.tool.id === tool.id);
  const updated = exists
    ? current.filter((item) => item.tool.id !== tool.id)
    : [
        {
          id: `saved-${tool.id}-${Date.now()}`,
          tool,
          categoryName,
          savedAt: new Date().toISOString(),
          planTitle,
        },
        ...current,
      ];
  window.localStorage.setItem(SAVED_TOOLS_KEY, JSON.stringify(updated));
  return updated;
}

export function getUserSettings(): UserSettings {
  if (typeof window === "undefined") return DEFAULT_SETTINGS;
  try {
    const raw = window.localStorage.getItem(SETTINGS_KEY);
    return raw
      ? { ...DEFAULT_SETTINGS, ...(JSON.parse(raw) as Partial<UserSettings>) }
      : DEFAULT_SETTINGS;
  } catch {
    return DEFAULT_SETTINGS;
  }
}

export function saveUserSettings(settings: UserSettings): UserSettings {
  if (typeof window === "undefined") return settings;
  window.localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));
  return settings;
}

export function generateMarkdownExport(plan: BuildPlan): string {
  const budget = calculatePlanBudget(plan);
  const isINR = plan.region === "INR";
  const sym = isINR ? "₹" : "$";
  const monthlyVal = isINR ? budget.monthlyTotalINR : budget.monthlyTotalUSD;
  const threeMoVal = isINR
    ? budget.threeMonthTotalINR
    : budget.threeMonthTotalUSD;

  const lines: string[] = [
    `# ${plan.title}`,
    `> Generated by **Buildsy.** — Budget-Disciplined MVP Build Plan`,
    `> Last Pricing Check: ${new Date(plan.lastPriceCheckAt).toLocaleDateString()}`,
    "",
    `## 1. Product Idea Overview`,
    `${plan.ideaDescription}`,
    "",
    `**Strategy Summary:** ${plan.summaryNote}`,
    "",
    `## 2. Total Estimated MVP Budget (Solo Founder / 1-Person Company)`,
    `- **Monthly Recurring Cost:** ${sym}${monthlyVal.toLocaleString()} / month (${plan.costBadge})`,
    `- **Initial 3-Month MVP Total (Phased):** ${sym}${threeMoVal.toLocaleString()}`,
    `- **Estimated 3-Month Savings vs. Upfront Scale Purchasing:** ${sym}${(isINR
      ? budget.savedThreeMonthsINR
      : budget.savedThreeMonthsUSD
    ).toLocaleString()}`,
    "",
    `### Category Breakdown (Monthly)`,
    `- **Development:** ${sym}${(isINR
      ? budget.breakdown.Development.inr
      : budget.breakdown.Development.usd
    ).toLocaleString()}`,
    `- **Design:** ${sym}${(isINR
      ? budget.breakdown.Design.inr
      : budget.breakdown.Design.usd
    ).toLocaleString()}`,
    `- **Database & Infra:** ${sym}${(isINR
      ? budget.breakdown["Database & Infra"].inr
      : budget.breakdown["Database & Infra"].usd
    ).toLocaleString()}`,
    `- **Marketing:** ${sym}${(isINR
      ? budget.breakdown.Marketing.inr
      : budget.breakdown.Marketing.usd
    ).toLocaleString()}`,
    `- **Other / Ops:** ${sym}${(isINR
      ? budget.breakdown.Other.inr
      : budget.breakdown.Other.usd
    ).toLocaleString()}`,
    "",
    `## 3. Recommended Tool Stack`,
  ];

  for (const cat of plan.categories) {
    const selected =
      cat.options.find((o) => o.id === cat.selectedToolId) || cat.options[0];
    lines.push(`### ${cat.name} (${cat.budgetGroup})`);
    lines.push(
      `- **Selected Tool:** **${selected.name}** (${selected.priceDisplay}) — *${selected.tagline}*`
    );
    lines.push(`- **Buy Phase:** ${selected.buyPhase}`);
    lines.push(`- **Why Recommended:** ${selected.whyRecommended}`);
    lines.push(`- **Free Tier Limits:** ${selected.freeTierLimits}`);
    lines.push(`- **When to Upgrade:** ${selected.whenToUpgrade}`);
    lines.push(
      `- **Alternatives in Stack:** ${cat.options
        .filter((o) => o.id !== selected.id)
        .map((o) => `${o.name} (${o.priceDisplay})`)
        .join(", ")}`
    );
    lines.push("");
  }

  lines.push(`## 4. Phased Buying Plan (Spend Only When Needed)`);
  for (const phase of plan.phases) {
    lines.push(`### ${phase.title}`);
    lines.push(`*Trigger:* ${phase.milestoneTrigger}`);
    lines.push(`**Activate / Buy Now:**`);
    for (const item of phase.whatToBuyNow) {
      lines.push(
        `- **${item.toolName}** (${item.costDisplay}): ${item.actionNote}`
      );
    }
    lines.push(`**Wait On (Do NOT Buy Yet):**`);
    for (const wait of phase.whatToWaitOn) {
      lines.push(
        `- ❌ **${wait.item}** — ${wait.reasonToWait} *(Saves ~$${wait.savedAmountUSD}/mo)*`
      );
    }
    lines.push("");
  }

  lines.push(`## 5. Common Overspend Traps to Avoid`);
  for (const trap of plan.overspendTraps) {
    lines.push(`- **${trap.title}:** ${trap.smartAlternative}`);
  }

  lines.push("");
  lines.push(
    `---`,
    `*Disclaimer: This is a point-in-time estimate generated by Buildsy. Tool pricing, free tiers, and available options change frequently — check back regularly for updated recommendations.*`
  );

  return lines.join("\n");
}
